### ISSUE TITLE
Add no-token CSS class for GraphiQL helpers not needing auth

### ISSUE THREAD

**Issue by jrebecchi** [krypton-org/krypton-auth#27]

**Comment by jrebecchi** [comment]
Finally I could manage to achieve it without this supplementary CSS class.

It is in the function `isAuthRequired` line 14 in [docs/_static/queries.js](https://github.com/jrebecchi/GraphQL-Auth-Service/blob/master/docs/_static/queries.js).

**Comment by maxmouchet** [comment]
https://github.com/jrebecchi/GraphQL-Auth-Service/commit/e09030f2b347429f18083e3fa7b4ee4404985123 + https://github.com/maxmouchet/sphinx-plugins/commit/91e3b91f34a7ad9634095301163cc5b57f1bf74a.

It adds the `with-token` CSS class. I think it makes more sense for the default to be "no token".

@jrebecchi I let you make the necessary JS modification.
