### ISSUE TITLE
Make notification field optional in GraphQL queries

### ISSUE THREAD

**Issue by maxmouchet** [krypton-org/krypton-auth#33]

**Comment by jrebecchi** [comment]
It is not possible to return null in GraphQL. However instead of returning an array of Notifications, we could return a simple boolean. Returnning `true` would mean that the operations has been completed.

A query like this :

```javascript
mutation{
  updateMe(fields:{username:"toto"})
}
```

would return this:

```
{
  "data": {
    "updateMe": true
  }
}

What do you think?
```

**Comment by jrebecchi** [comment]
Reviewing the code, I can see there is a case where a couple of notification are sent for one mutation:
`register`. It returns a notification that the user has been created and that an email was sent to confirm his email. Returning only `true` to that mutation means that we would put all this logic to the client. It could be, as we already decided to put internationalization on the client.

**Comment by maxmouchet** [comment]
Sounds good :-)
