### ISSUE TITLE
Add UnauthorizedError

### ISSUE THREAD

**Issue by maxmouchet** [krypton-org/krypton-auth#38]
- Use `UserNotFound` for the `login` mutation
- Use `UnauthorizedError` for the other mutations/queries when the token is not present / invalid.  

- [x] Code  
- [x] Documentation (https://github.com/krypton-org/krypton-auth/blob/master/docs/queries.rst)

**Comment by jrebecchi** [comment]
`login`, `updateMe`, `refreshToken` mutaiton may also send a `TokenEncryptionError`. It can occur only if the service has been wrongly configured, like with a wrong format for the private key or with a wrong encoding algorithm chosen.
