### ISSUE TITLE
Removing hasUsername property

### ISSUE THREAD

**Issue by jrebecchi** [krypton-org/krypton-auth#40]
For further simplicity, we should let users define a possible username in the `extendedSchema` property and provide a little recipe on how to add it, in the documentation, in a cookbook category.

**Comment by maxmouchet** [comment]
+1 for the cookbook category.
I would also add the `role` (user, admin, ...) field in it.

**Comment by jrebecchi** [comment]
For the moment there is no admin users in Krypton Authentication. It would suppose users with special rights like editing/removing/creating other users. It is definitely a feature to implement!!

But I don't think we can let the client decide whether it creates a regular user or an admin. As anyone could register as an admin so. We could define a kind of superuser server-side who could send emails containing a link to create an admin account. It would also be whitelist of emails defined server-side that can receive this invitation.

**Comment by maxmouchet** [comment]
I was more thinking of "admin" from the application point-of-view, not krypton-auth :-)  
For example in your own app, you can have admins, free users, paid users, ...

**Comment by jrebecchi** [comment]
Don't you think we could add it in the `extendedSchema` and provide it in the cookbook?
`
extendedSchema: {
    role: {
        type: String,
        required: true,
        enum: ["User", "Member", "Admin"],
        isPublic: false
    }
}
`
