### ISSUE TITLE
Retry the connection to the database when the server is unavailable

### ISSUE THREAD

**Issue by maxmouchet** [krypton-org/krypton-auth#46]
Currently the application crash.

**Comment by jrebecchi** [comment]
Indeed important issue to solve. Thanks Max for the notice!

**Comment by jrebecchi** [comment]
Connection to mongodb through Mongoose or Agenda has to be done with the property [`useUnifiedTopology`](https://mongodb.github.io/node-mongodb-native/3.5/reference/unified-topology/), properties like `autoReconnect`, `reconnectTries` and `reconnectInterval` are [deprecated](https://mongodb.github.io/node-mongodb-native/3.5/reference/unified-topology/).

With `useUnifiedTopology` activated the default delay to connect to the database is 30 seconds. It can be changed into the connection string of mongodb with the property [serverSelectionTimeoutMS](https://docs.mongodb.com/manual/reference/connection-string/#urioption.serverSelectionTimeoutMS). 

To set the timeout to a minute, we would have to pass to Krypton `dbAddress` property something like: `mongodb://localhost:27017/users?serverSelectionTimeoutMS=60000`.
