### ISSUE TITLE
Show the Explorer and Query variables tab in GraphiQL by default

### ISSUE THREAD

**Issue by nicobao** [krypton-org/krypton-auth#58]
Show the Explorer and Query variables tab in GraphiQL by default. Like in the Gatsby Project

![Gatsby example](https://user-images.githubusercontent.com/46368291/80973504-bfba2800-8e1f-11ea-8a72-10cca0e9000e.png)

Config to tweak:

docExplorerOpen: an optional boolean which when true will ensure the DocExplorer is open by default when the user first renders the component. If the user has toggled the doc explorer on/off following this, however, the persisted UI state will override this default flag.

defaultVariableEditorOpen = true

Edit the configuration variables here:
https://github.com/krypton-org/krypton-auth/blob/master/src/graphiql/renderGraphiQL.ts#L142

**Comment by jrebecchi** [comment]
Thanks for the issue with the solution included!
It will be in the next release of Krypton Authentication.
